# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=8, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tname', models.CharField(blank=True, max_length=8, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sc',
            name='student',
            field=models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='tno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='sc',
            unique_together=set([('student', 'course')]),
        ),
    ]
